# Generated by Django 5.0.6 on 2024-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_alter_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='shedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
            ],
        ),
    ]
