# Generated by Django 5.0.6 on 2024-06-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_shedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('number_plate', models.CharField(verbose_name=15)),
                ('status', models.BooleanField(default=0)),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.shedules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.customer_data')),
            ],
        ),
    ]
