# Generated by Django 5.0.6 on 2024-06-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_customer_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_booking',
            old_name='shedule',
            new_name='schedule',
        ),
    ]
