# Generated by Django 5.0.6 on 2024-07-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0007_alter_customer_booking_number_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('two wheel', 'two wheel'), ('for wheel', 'for wheel'), ('heavy vehicle', 'heavy vehicle')], max_length=50)),
                ('complaint_description', models.TextField(null=True)),
                ('work_status', models.CharField(choices=[('Work started', 'Work started'), ('Work on progres', 'work on progres'), ('work compleated', 'work compleated')], max_length=50)),
                ('estimate_cost', models.CharField(max_length=20)),
                ('Name_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.manager_data')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.shedules')),
            ],
        ),
    ]
