# Generated by Django 5.0.6 on 2024-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0008_create_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='complaint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='create_work',
            name='estimate_cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='create_work',
            name='vehicle',
            field=models.CharField(choices=[('two wheel', 'two wheel'), ('for wheel', 'for wheel'), ('heavy vehicle', 'heavy vehicle')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='create_work',
            name='work_status',
            field=models.CharField(choices=[('Work started', 'Work started'), ('Work on progres', 'work on progres'), ('work compleated', 'work compleated')], max_length=50, null=True),
        ),
    ]
