# Generated by Django 5.0.6 on 2024-07-01 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0009_alter_create_work_complaint_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.customer_booking'),
        ),
    ]
