# Generated by Django 5.0.6 on 2024-07-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0010_alter_create_work_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_work',
            old_name='schedule',
            new_name='name_of_car',
        ),
    ]
