# Generated by Django 5.0.6 on 2024-07-02 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0011_rename_schedule_create_work_name_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='name_of_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.customer_booking'),
        ),
        migrations.AlterField(
            model_name='create_work',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('two wheel', 'two wheel'), ('for wheel', 'for wheel'), ('heavy vehicle', 'heavy vehicle')], max_length=50, null=True),
        ),
    ]
