# Generated by Django 5.0.6 on 2024-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0012_alter_create_work_name_of_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='work_status',
            field=models.CharField(blank=True, choices=[('Work started', 'Work started'), ('Work on progres', 'work on progres'), ('work compleated', 'work compleated')], max_length=50, null=True),
        ),
    ]
