# Generated by Django 5.0.6 on 2024-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0014_rename_name_of_car_create_work_customer_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('sedan', 'sedan'), ('SUV', 'SUV'), ('hatchback', 'hatchback'), ('others', 'others')], max_length=50, null=True),
        ),
    ]
