# Generated by Django 5.0.6 on 2024-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0015_alter_create_work_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_work',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
