# Generated by Django 5.0.6 on 2024-07-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0016_create_work_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=3)),
                ('expiry_date', models.CharField(max_length=7)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.create_work')),
            ],
        ),
    ]
