# Generated by Django 5.0.6 on 2024-07-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.shedules'),
        ),
        migrations.AlterField(
            model_name='customer_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer_data'),
        ),
    ]
