# Generated by Django 5.0.6 on 2024-07-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0018_alter_customer_booking_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_work',
            name='Name_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.manager_data'),
        ),
        migrations.AlterField(
            model_name='create_work',
            name='customer_booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_app.customer_booking'),
        ),
    ]
